"""Moderator Agent — synthesises the three specialist opinions.

Key invariants enforced by THIS module (not by the LLM prompt alone):

1. `points_of_disagreement` is NEVER an empty list. If the LLM returns
   nothing, the wrapper injects:
   "No material disagreement among the panel."
   The brief calls this out explicitly: disagreement must not be smoothed
   into false certainty, and an empty list IS smoothing.

2. The MedBridge disclaimer is appended by the wrapper, not generated by
   the LLM, so a wonky LLM response can never drop it.

Offline fallback returns a deterministic synthesis derived from the stub
opinions, also honouring both invariants above.
"""

from __future__ import annotations

import json
import logging
import os

from ..db.db import get_conn
from ..models import ConsensusReport, SpecialistOpinion
from .jsonutil import extract_first_json

logger = logging.getLogger("medbridge.moderator")

_GEMINI_MODEL = os.environ.get("GEMINI_MODEL", "gemini-2.5-flash")

DEFAULT_DISCLAIMER = (
    "This synthesis is an AI-generated observation, not a medical diagnosis. "
    "Please consult a licensed physician before acting on it."
)

NO_DISAGREEMENT_SENTENCE = "No material disagreement among the panel."


def _stub_synthesis(opinions: list[SpecialistOpinion]) -> ConsensusReport:
    """Deterministic fallback so the demo still works without an API key."""
    by_type = {o.specialist_type: o for o in opinions}
    agree: list[str] = []
    disagree: list[str] = []

    # Build agreement by intersecting flags.
    flag_sets = [set(o.flags) for o in opinions]
    common = set.intersection(*flag_sets) if flag_sets else set()
    for f in sorted(common):
        agree.append(f"All three specialists flagged '{f}'.")

    # Build disagreement by symmetric differences.
    for a in opinions:
        for b in opinions:
            if a.specialist_type >= b.specialist_type:
                continue
            only_a = set(a.flags) - set(b.flags)
            only_b = set(b.flags) - set(a.flags)
            if only_a:
                disagree.append(
                    f"{a.specialist_type} raised {sorted(only_a)} which "
                    f"{b.specialist_type} did not."
                )
            if only_b:
                disagree.append(
                    f"{b.specialist_type} raised {sorted(only_b)} which "
                    f"{a.specialist_type} did not."
                )

    confidences = ", ".join(f"{o.specialist_type}={o.confidence:.2f}" for o in opinions)
    summary = (
        "Specialists reviewed the report independently. "
        f"Stated confidences: {confidences}. "
        f"Cardiology view: {by_type.get('cardiology').findings[:120] if 'cardiology' in by_type else ''} "
    ).strip()

    return ConsensusReport(
        summary=summary,
        points_of_agreement=agree or ["All three specialists reviewed the same report text."],
        points_of_disagreement=disagree or [NO_DISAGREEMENT_SENTENCE],
        disclaimer=DEFAULT_DISCLAIMER,
    )


def _ensure_invariants(report: ConsensusReport) -> ConsensusReport:
    """Inject required defaults if the LLM left them empty."""
    if not report.points_of_disagreement:
        report.points_of_disagreement = [NO_DISAGREEMENT_SENTENCE]
    if not report.points_of_agreement:
        report.points_of_agreement = ["All three specialists reviewed the same report text."]
    if not report.disclaimer or "diagnosis" not in report.disclaimer.lower():
        report.disclaimer = DEFAULT_DISCLAIMER
    return report


def synthesize(opinions: list[SpecialistOpinion], report_id: int) -> ConsensusReport:
    """Call the Moderator LLM (or fall back), persist, return."""
    if not os.environ.get("GEMINI_API_KEY"):
        logger.info("No GEMINI_API_KEY — using stub moderator")
        consensus = _stub_synthesis(opinions)
    else:
        try:
            from crewai import Agent, Crew, LLM, Task  # type: ignore
            llm = LLM(model=f"gemini/{_GEMINI_MODEL}", api_key=os.environ["GEMINI_API_KEY"])
            agent = Agent(
                role="Clinical Moderator",
                goal=(
                    "Synthesise three specialist opinions into a structured consensus "
                    "report that honestly surfaces disagreement."
                ),
                backstory=(
                    "You aggregate cardiology, internal medicine, and radiology "
                    "perspectives. You NEVER smooth disagreement into false certainty. "
                    "If the panel agrees on a point, list it. If they disagree on "
                    "findings, severity, or recommended next steps, list each "
                    "disagreement separately. If there is truly no disagreement, "
                    f"return ['{NO_DISAGREEMENT_SENTENCE}'] — never an empty list."
                ),
                llm=llm,
                verbose=False,
                allow_delegation=False,
            )
            payload = [o.model_dump() for o in opinions]
            task = Task(
                description=(
                    "Synthesise the following three specialist opinions. "
                    "Return ONLY a JSON object — no prose around it — matching:\n"
                    "{\n"
                    '  "summary": "<3-5 sentence neutral synthesis>",\n'
                    '  "points_of_agreement": ["..."],\n'
                    '  "points_of_disagreement": ["..."],\n'
                    f'  "disclaimer": "{DEFAULT_DISCLAIMER}"\n'
                    "}\n"
                    "Rules:\n"
                    "- points_of_disagreement MUST NOT be empty. If they truly agree, "
                    f"use [\"{NO_DISAGREEMENT_SENTENCE}\"].\n"
                    "- Do not invent findings not present in any opinion.\n"
                    "- Conclude the summary with a recommendation to consult a "
                    "licensed physician.\n\n"
                    "--- Specialist opinions (JSON) ---\n"
                    f"{json.dumps(payload, indent=2)}\n"
                    "--- End ---"
                ),
                expected_output="A single JSON object matching the schema.",
                agent=agent,
            )
            crew = Crew(agents=[agent], tasks=[task], verbose=False)
            raw = str(crew.kickoff())
            parsed = extract_first_json(raw)
            if parsed is None:
                raise ValueError("could not parse JSON from moderator output")
            consensus = ConsensusReport(**parsed)
        except Exception as exc:
            logger.warning("Moderator LLM failed: %s — falling back to stub", exc)
            consensus = _stub_synthesis(opinions)

    consensus = _ensure_invariants(consensus)
    consensus.report_id = report_id

    conn = get_conn()
    conn.execute(
        """INSERT INTO ConsensusReport(report_id, summary, disagreement_notes)
           VALUES(?,?,?)""",
        (
            report_id,
            consensus.summary,
            json.dumps({
                "agreement": consensus.points_of_agreement,
                "disagreement": consensus.points_of_disagreement,
                "disclaimer": consensus.disclaimer,
            }),
        ),
    )
    conn.commit()
    return consensus
